import numpy as np


class ISACConfig:
    """
    Store all constant parameters related to ISAC.
    """
    def __init__(self):
        self.Nt = 12          # transmit antenna
        self.Nr = 10          # receiving antenna
        self.L = 10            # DFRC frame length
        self.lambda_ = 1.0
        self.d = self.lambda_ / 2  # half-wavelength spacing
        self.alpha = 0.5

        # Noise power (dBm), the default is 0 dBm
        self.sigma2C_dBm = 0.0
        self.sigma2R_dBm = 0.0

        # Scale factor, exactly the same as in MATLAB
        self.scale_factor_W = 100.0
        self.scale_factor_CRB = 100.0

        self.n_t = np.arange(-(self.Nt - 1) / 2.0, (self.Nt - 1) / 2.0 + 1.0, 1.0, dtype=np.float64).reshape(-1, 1)
        self.n_r = np.arange(-(self.Nr - 1) / 2.0, (self.Nr - 1) / 2.0 + 1.0, 1.0, dtype=np.float64).reshape(-1, 1)

    @property
    def k0(self):
        return 2.0 * np.pi / self.lambda_

    @property
    def sigma2C(self):
        # dBm -> Watt: 10^((dBm - 30)/10)
        return 10.0 ** ((self.sigma2C_dBm - 30.0) / 10.0)

    @property
    def sigma2R(self):
        return 10.0 ** ((self.sigma2R_dBm - 30.0) / 10.0)

    def PT(self, P_dB):
        return 10.0 ** ((P_dB - 30.0) / 10.0)

    def Gamma(self, Gamma):
        return 10.0 ** (Gamma / 10.0)


def compact_vector_to_W(w_vec):
    """
    Convert a real-valued vector of length 2Nt into an Nt x Nt Hermitian complex matrix W.
    w_vec = [Re(w_1), ..., Re(w_Nt), Im(w_1), ..., Im(w_Nt)]
    """

    Nt = w_vec.size // 2
    w_real = w_vec[:Nt]
    w_imag = w_vec[Nt:]

    # w ∈ C^{Nt}
    w = w_real + 1j * w_imag  # shape: (Nt,)

    # W = w w^H
    W = np.outer(w, np.conjugate(w))  # (Nt, Nt)

    return W


def vectors_to_W_stack(w_pred_vectors_scaled, config, K):
    """
    Convert the compact vector output by the model back into a stack of complex matrices with shape (K, Nt, Nt).
    Note that the model output W is scaled, so it needs to be restored to the original data scale.

    Input:
    W_pred_vectors_scaled: the processed raw model output, in list form, with length 2*K*Nt
    config: an ISACConfig instance (providing Nt and scale_factor_W)
    K: number of users

    Output:
    W_stack: restored Hermitian complex matrices with shape (K, Nt, Nt), where each W_k has been divided by scale_factor_W
    """
    Nt = config.Nt
    scale_factor_W = config.scale_factor_W
    arr = np.asarray(w_pred_vectors_scaled, dtype=float)

    # Restore to Reality W
    W_stack = np.zeros((K, Nt, Nt), dtype=np.complex128)
    for k in range(K):
        base_index = k * 2 * Nt
        w_unscaled = arr[base_index: base_index + 2 * Nt] / scale_factor_W
        Wk = compact_vector_to_W(w_unscaled)
        W_stack[k] = Wk
    return W_stack


def compute_channel_H(input_obj):
    """
     Parse the channel matrix H from the input
    """
    H_real = np.asarray(input_obj["H_real"], dtype=float)
    H_imag = np.asarray(input_obj["H_imag"], dtype=float)
    H = H_real + 1j * H_imag
    return H


def compute_radar_A(config, theta):
    """
    Compute the radar angle matrix A and its derivative Ȧ for the CRB
    """
    k0 = config.k0
    d = config.d

    n_t = config.n_t
    n_r = config.n_r

    a_theta = np.exp(1j * k0 * d * n_t * np.sin(theta))  # (Nt,1)
    b_theta = np.exp(1j * k0 * d * n_r * np.sin(theta))  # (Nr,1)

    # A(θ) = b(θ) a^H(θ)
    A = b_theta @ a_theta.conj().T

    # Ȧ(θ) = ḃ(θ)a^H(θ) + b(θ)ȧ^H(θ)
    a_dot = 1j * k0 * d * n_t * np.cos(theta) * a_theta
    b_dot = 1j * k0 * d * n_r * np.cos(theta) * b_theta
    Ad = b_dot @ a_theta.conj().T + b_theta @ a_dot.conj().T

    return A, Ad


def compute_crb_for_sample(config, theta, W_stack):
    """
    Compute the CRB of one sample in the same way as in MATLAB.

    ## Parameters
    config : ISACConfig
    An instance of the configuration class above, which stores system constants, noise, and scaling factors.
    theta : radar angle in radians
    W_stack : the parsed model output Wk, the beamforming matrix for each user

    ## Returns
    crb_scaled : float
    = CRB_deg2 * config.scale_factor_CRB
    It can be directly compared with the "objective" in the data generated by your MATLAB code.
    """
    L = config.L
    alpha = config.alpha

    sigma2R = config.sigma2R

    # R_X = sum_k W_k
    RX = np.sum(W_stack, axis=0)

    # n_t, n_r
    A, Ad = compute_radar_A(config, theta)

    # CRB computing according to the matlab
    num_CRB = sigma2R * np.trace(A.conj().T @ A @ RX)

    # 分母
    term1 = np.trace(Ad.conj().T @ Ad @ RX)
    term2 = np.trace(A.conj().T @ A @ RX)
    term3 = np.trace(Ad.conj().T @ A @ RX)
    den_CRB = 2.0 * (abs(alpha) ** 2) * L * (term1 * term2 - abs(term3) ** 2)

    num_real = float(np.real(num_CRB))
    den_real = float(np.real(den_CRB))

    if den_real <= 0 or abs(den_real) < 1e-12:
        CRB_rad = float("inf")
    else:
        CRB_rad = num_real / den_real

    # CRB_deg2（deg）
    CRB_deg = CRB_rad * (180.0 / np.pi) ** 2
    CRB_deg2 = float(np.sqrt(max(CRB_deg, 0.0)))

    # Multiply by the scaling factor again to match the objective in the dataset.
    crb_scaled = CRB_deg2 * config.scale_factor_CRB
    # Keep three decimal places to stay consistent with the dataset results.
    crb_scaled = float(np.round(crb_scaled, 3))

    return crb_scaled
